{
  "Uuid": "ac2b3126-ca80-416f-8ad5-366b06a31960",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Tab Select Elements",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\n\r\nclr.AddReference('RevitServices')\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\nuidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument\r\n\r\n\"\"\"\r\nhttps://www.revitapidocs.com/2022/8eccaa93-cc99-fd37-15ad-24d201985d9b.htm\r\n\r\nhttps://www.revitapidocs.com/2022/d9848d7d-5917-2433-8454-f65f5ac03964.htm\r\n\"\"\"\r\n\r\ndef get_current_selection (uidoc):\r\n\tsel = uidoc.Selection\r\n\treturn sel.GetElementIds()\r\n\t\r\nselected_elements = []\r\nfor i in get_current_selection(uidoc):\r\n\tselected_elements.append(doc.GetElement(i))\r\n\r\nOUT = selected_elements",
      "Engine": "IronPython2",
      "VariableInputPorts": true,
      "Id": "8faa4e1470bf4e7e82d47921e1c0f348",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "ea4c072446e3439886f85cdcb1c5c458",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded Python script."
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "\r\n\"\"\"\r\n\r\nC:\\Program Files\\Autodesk\\Revit 2022\\AddIns\\DynamoForRevit\r\n\r\nC:\\Program Files\\Autodesk\\Revit 2022\\AddIns\\DynamoForRevit\\Revit\r\n\r\n\"\"\"\r\n\r\nimport clr\r\n#clr.AddReference('ProtoGeometry')\r\n#from Autodesk.DesignScript.Geometry import *\r\n\r\nclr.AddReference('DynamoRevitDS')\r\nimport Dynamo\r\n#access to the current Dynamo instance and workspace\r\ndynamoRevit = Dynamo.Applications.DynamoRevit()\r\ncurrentWorkspace = dynamoRevit.RevitDynamoModel.CurrentWorkspace\r\n\r\ndef onEvaluationcompleted(obj, e):\r\n\tfor i in currentWorkspace.Nodes:\r\n\t\tif i.Name.StartsWith(\"*Force\"):\r\n\t\t\ti.MarkNodeAsModified(True)\r\n#the handlers for when a script has been run\r\ncurrentWorkspace.EvaluationCompleted += onEvaluationcompleted",
      "Engine": "IronPython2",
      "VariableInputPorts": true,
      "Id": "4b883fde0b27477b922bc1b5c1af96b8",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "204154102adb4d92ad95d8fe40897c10",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded Python script."
    }
  ],
  "Connectors": [],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.12",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.12.0.5650",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -1217.5709228515625,
      "EyeY": 135.99923706054688,
      "EyeZ": 1367.35302734375,
      "LookX": 12.8519287109375,
      "LookY": -9.6659088134765625,
      "LookZ": -9.272705078125,
      "UpX": 0.26402744650840759,
      "UpY": 0.94551855325698853,
      "UpZ": -0.19048435986042023
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "*Force Get Active Selection",
        "Id": "8faa4e1470bf4e7e82d47921e1c0f348",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -365.02350115618884,
        "Y": -839.05099308012643
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "4b883fde0b27477b922bc1b5c1af96b8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -406.55272022223232,
        "Y": -447.39600335302248
      }
    ],
    "Annotations": [
      {
        "Id": "036eb5dd73a143d1b9093ddcecd25fb2",
        "Title": "https://forum.dynamobim.com/t/how-to-force-nodes-to-rerun-without-changes-when-nodes-rerun/56366/3",
        "Nodes": [],
        "Left": -401.80506426748934,
        "Top": -349.8708610976264,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      }
    ],
    "X": 580.38152256316016,
    "Y": 1191.7268449001767,
    "Zoom": 1.3664659088667033
  }
}